---
x-prepare: &install_prepare
  run:
    name: "Install/Upgrade tox & pip"
    command: |
      sudo chown -R circleci:circleci /usr/local/bin
      sudo chown -R circleci:circleci /usr/local/lib/python$(python --version | sed -e 's/Python\s//g' | awk -F'.' '{print $1"."$2}')/site-packages
      pip install pip tox --upgrade
x-test-steps: &test_steps
  working_directory: ~/app
  steps:
    - checkout
    - <<: *install_prepare
    - run:
        name: Mighty test run
        command: tox -e test_ci
x-docker-env: &postgres_env
  environment:
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_DB: test

version: 2.1
jobs:
  verify:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - <<: *install_prepare
      - run:
          name: Check formatting
          command: tox -e yapf
      - run:
          name: Check mypy
          command: tox -e mypy
      - run:
          name: Check flake
          command: tox -e flake8
  test_36:
    <<: *test_steps
    docker:
      - image: circleci/python:3.6.8
      - image: postgres:alpine
        <<: *postgres_env
  test_373:
    <<: *test_steps
    docker:
      - image: circleci/python:3.7.3
      - image: postgres:alpine
        <<: *postgres_env
  test_374:
    <<: *test_steps
    docker:
      - image: circleci/python:3.7.4
      - image: postgres:alpine
        <<: *postgres_env

workflows:
  version: 2
  apg-m-verify:
    jobs:
      - verify
      - test_36
      - test_373
      - test_374
