---
x-install-tox: &install_tox
  run:
    name: "Install/Upgrade tox & pip"
    command: |
      pip install pip tox --upgrade
x-test-steps: &test_steps
  working_directory: ~/app
  steps:
    - checkout
    - <<: *install_tox
    - run:
        name: Unit test
        command: tox -e test_unit
version: 2.1
jobs:
  verify:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - <<: *install_tox
      - run:
          name: Check formatting
          command: tox -e yapf
      - run:
          name: Check mypy
          command: tox -e mypy
      - run:
          name: Check flake
          command: tox -e flake8
      - run:
          name: Unit test
          command: tox -e test_unit
  test_35:
    <<: *test_steps
    docker:
      - image: circleci/python:3.5.7
  test_36:
    <<: *test_steps
    docker:
      - image: circleci/python:3.6.8
  test_37:
    <<: *test_steps
    docker:
      - image: circleci/python:3.7.3

workflows:
  version: 2
  apg-m-verify::
    jobs:
      - verify
      - test_35:
          requires:
            - verify
      - test_36:
          requires:
            - verify
      - test_37:
          requires:
            - verify
