---
version: "3.7"

services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file: env

  adminer:
    image: dpage/pgadmin4:latest
    container_name: helion_db_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: helion@helion.pl
      PGADMIN_DEFAULT_PASSWORD: helion
    ports:
      - 8080:80
    depends_on:
      - postgres

  tests:
    image: asynpg_migrate_integration:latest
    restart: "no"
    env_file: env
    depends_on:
      - postgres
